alias dcd="docker-compose down"
alias dce="docker-compose exec"
alias dcr="docker-compose run"
alias dcu="docker-compose up"
alias dcub="docker-compose up --build"
alias dcl="docker-compose logs"
alias dclt="dcl -tf"
alias dockercleanup="docker rmi -f \$(docker images -qf dangling=true); docker volume rm \$(docker volume ls -qf dangling=true)"
