alias dcb="docker compose build"
alias dcd="docker compose down"
alias dce="docker compose exec"
alias dcl="docker compose logs"
alias dclt="dcl -tf"
alias dcr="docker compose run --rm"
alias dcu="docker compose up"
alias dcub="docker compose up --build"
alias dockercleanup="docker rmi -f \$(docker images -qf dangling=true); docker volume rm \$(docker volume ls -qf dangling=true)"
