for config_file in `ls $HOME/.zsh/lib/*.zsh`; do source $config_file; done

source "$HOME/.zsh/theme.zsh"

## Aliases
for alias_file in `ls $HOME/.zsh/aliases/*.zsh`; do source $alias_file; done
# Machine specific aliases
[[ -s $HOME/.aliases ]] && source $HOME/.aliases

export PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH

export TERM=xterm-256color

## Editors
export EDITOR=vim
export BUNDLER_EDITOR=$EDITOR

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Custom extensions (outside dotfiles)
[[ -s $HOME/.zsh-custom ]] && source $HOME/.zsh-custom
